import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/state/redux/ReduxProvider";
import AppBar from "@/components/AppBar";
import AppThemeContextProvider from "@/state/context/AppThemeContext";
import GadgetsContextProvider from "@/state/context/GadgetsContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <Provider store={store}> */}
        <ReduxProvider>
          {/* <AppThemeContext.Provider value={initialThemeState}> */}
          <AppThemeContextProvider>
            <GadgetsContextProvider>
            <div className="container">
              <AppBar />
              <main>
                {children}
              </main>
            </div>
            </GadgetsContextProvider>
          </AppThemeContextProvider>
          {/* </AppThemeContext.Provider> */}
        </ReduxProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
